// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gspvigweloaaombljqor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzcHZpZ3dlbG9hYW9tYmxqcW9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MTYwMzUsImV4cCI6MjA3MTM5MjAzNX0.wTwYgpAJlXvzNj41en6ZZQ1WfktiKKDyd8BQRehCpN4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});